apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: credentials
  name: credentials
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: credentials
    spec:
      containers:
      - args:
        - bash
        - -c
        - source /edx/app/credentials/credentials_env && while true; do python /edx/app/credentials/credentials/manage.py
          runserver 0.0.0.0:18150; sleep 2; done
        env:
        - name: CACHE_LOCATION
          value: edx.devstack.memcached:12211
        - name: DB_HOST
          value: edx.devstack.mysql
        - name: ENABLE_DJANGO_TOOLBAR
          value: "1"
        - name: SOCIAL_AUTH_EDX_OIDC_URL_ROOT
          value: http://edx.devstack.lms:18000/oauth2
        image: edxops/credentials:ironwood.master
        name: edx-devstack-credentials
        ports:
        - containerPort: 18150
        resources: {}
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /edx/app/credentials/credentials
          name: credentials-claim0
        - mountPath: /edx/app/credentials/credentials/node_modules
          name: credentials-node-modules
        - mountPath: /edx/src
          name: credentials-claim2
      hostname: credentials-devstack-edx
      restartPolicy: Always
      volumes:
      - name: credentials-claim0
        persistentVolumeClaim:
          claimName: credentials-claim0
      - name: credentials-node-modules
        persistentVolumeClaim:
          claimName: credentials-node-modules
      - name: credentials-claim2
        persistentVolumeClaim:
          claimName: credentials-claim2
status: {}
