apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: credentials
  name: credentials
spec:
  ports:
  - name: "18150"
    port: 18150
    targetPort: 18150
  selector:
    io.kompose.service: credentials
status:
  loadBalancer: {}
