kind: PersistentVolume
apiVersion: v1
metadata:
  name: edxapp-lms-assets-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /edx/var/edxapp/staticfiles/
