---
- hosts: mynodes2
  become: true
  tasks:
  - name: Updating apt-get repository
    shell: sudo apt-get update
  - name: Installing packages over http
    shell: sudo apt-get -y install \
           apt-transport-https \
         ca-certificates \
           curl \
            gnupg-agent \
            software-properties-common
  - name: Pulling gpg key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - name: Matching Fingerprint
    shell: sudo apt-key fingerprint 0EBFCD88
  - name: Updating Resources
    shell: sudo apt-get update
  - name: Adding repository
    shell: sudo add-apt-repository  "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - name: Installing Docker Engine
    shell: sudo apt-get -y install docker-ce docker-ce-cli containerd.io 
  - name: Installing docker-compose
    shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - name: Giving executable permissions
    shell: sudo chmod +x /usr/local/bin/docker-compose
  - name: Installing docker machine
    shell: base=https://github.com/docker/machine/releases/download/v0.16.0 && curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine &&  sudo install /tmp/docker-machine /usr/local/bin/docker-machine




