kind: PersistentVolume
apiVersion: v1
metadata:
  name: chrome-volume0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /edx/app/e2e/edx-e2e-tests/upload_files
