kind: PersistentVolume
apiVersion: v1
metadata:
  name: discovery-node-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /edx/app/discovery/discovery/node_modules
