apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-host.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: ecommerce
  name: ecommerce
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ecommerce
    spec:
      containers:
      - image: ecommerce
        name: ecommerce
        resources: {}
        volumeMounts:
        - mountPath: /edx/app/ecommerce/ecommerce
          name: ecommerce-claim0
        - mountPath: /edx/app/ecommerce/ecommerce/node_modules
          name: ecommerce-node-modules
        - mountPath: /edx/src
          name: ecommerce-claim2
      restartPolicy: Always
      volumes:
      - name: ecommerce-claim0
        persistentVolumeClaim:
          claimName: ecommerce-claim0
      - name: ecommerce-node-modules
        persistentVolumeClaim:
          claimName: ecommerce-node-modules
      - name: ecommerce-claim2
        persistentVolumeClaim:
          claimName: ecommerce-claim2
status: {}
