kind: PersistentVolume
apiVersion: v1
metadata:
  name: edx-notes-api-volume0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /edx/app/edx_notes_api/edx_notes_api
