kind: PersistentVolume
apiVersion: v1
metadata:
  name: forum-volume0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /edx/app/forum/cs_comments_service
