apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-host.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: forum
  name: forum
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: forum
    spec:
      containers:
      - image: forum
        name: forum
        resources: {}
        volumeMounts:
        - mountPath: /edx/app/forum/cs_comments_service
          name: forum-claim0
      restartPolicy: Always
      volumes:
      - name: forum-claim0
        persistentVolumeClaim:
          claimName: forum-claim0
status: {}
