apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-host.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: gradebook
  name: gradebook
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gradebook
    spec:
      containers:
      - image: gradebook
        name: gradebook
        resources: {}
        volumeMounts:
        - mountPath: /edx/app/gradebook
          name: gradebook-claim0
        - mountPath: /edx/app/gradebook/node_modules
          name: gradebook-node-modules
      restartPolicy: Always
      volumes:
      - name: gradebook-claim0
        persistentVolumeClaim:
          claimName: gradebook-claim0
      - name: gradebook-node-modules
        persistentVolumeClaim:
          claimName: gradebook-node-modules
status: {}
