kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/mysql
